### ISSUE TITLE
[Bug]: MASSIVE lag - tons of mobs spawning

### ISSUE THREAD

**Issue by mateus3c** [Fuzss/respawninganimals#18]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.0

### Notes (Required)

Everytime I create a new world with this new version I get surrounded by more than 200 mobs, and that literally gets my FPS from 200+ to 3fps
[latest.log](https://github.com/Fuzss/respawninganimals/files/12363919/latest.log)

**Comment by Fuzss** [comment]
This seems like a mod conflict. I've made some minor changes now in v8.0.1 that should make it less likely for other mods to break Respawning Animals. If the new version still results in over-spawning it would be great if you could remove mods until you find which other mod is conflicting.

Please reopen the issue if it's not fixed in the new version.

**Comment by mateus3c** [comment]
the issue still persists on 8.1.1 

this bug doesnt happen on 8.0.0, so im sticking with it

**Comment by Fuzss** [comment]
Respawning Animals works fine on it’s own, so this is likely a mod conflict.

It would be great if you could remove mods until you find which other mod is conflicting so that I can fix this issue.

**Comment by Reshy** [comment]
This happens without Exotic Birds, it seems like whatever the bug is also overrides Incontrol's caps on spawning behavior.

![image](https://github.com/Fuzss/respawninganimals/assets/2096384/474e7d09-203f-44d0-b6b0-692172c76763)

**Comment by Spiderach** [comment]
This also seems to be happening with the quark Toretoise. It's spawning and lingering by the hundreds within short time frames.
I'm using the 1.18.2 version, and from what I can tell there's no config to blacklist certain mobs/mods to resolve the issue that way either.

**Comment by mateus3c** [comment]
it happens with many mods, enemy expansion, alex mobs, enhanced celestials… etc… guys, the bug doesn’t happen on version 8.0.0 i recommend the dev to check the differences made from 8.0.0 to the newer versions to find out what’s happening. 
also, it would be great to have the version 8.0.0 ported to 1.19.2 since the version on 1.19.2 as this horrible bug too. the only version I tested that doesn’t has this bug is 8.0.0.

**Comment by NolanHewitt** [comment]
![huge_2024-01-19_02 03 34](https://github.com/Fuzss/respawninganimals/assets/52480898/e751d203-430e-4759-b629-7f1b3a087a8e)
Spawns for naturalist animals go sicko mode with this mod installed.

**Comment by Fuzss** [comment]
Should all be fixed in v8.2.0, I specifically tested all the mods mentioned here.

@Reshy @jolandepoel Exotic Birds has a config option for allowing birds to despawn which is disabled by default. You'll have to enable that option to prevent excessive overspawning.
